### ISSUE TITLE
Application did not respond

### ISSUE THREAD

**Issue by LordEctelion** [mgiovani/my-instants-discord-bot#6]
Hi, just wanna inform that the bot does not respond to commands with a "The application did not respond" error message.

![issue](https://github.com/mgiovani/my-instants-discord-bot/assets/145809166/7108c205-0e2c-4227-b65b-01c3ea6ab3fb)

**Comment by mgiovani** [comment]
Hi @LordEctelion,

Thank you for taking the time to report this issue! [We’ve updated](https://github.com/mgiovani/my-instants-discord-bot/pull/8) the bot, and it should now be working as expected. We appreciate your patience and your help in making the bot better.

If you encounter any further issues, please don’t hesitate to let us know!
